patch edk2 source in CI aswell

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -30,10 +30,33 @@ steps:
       git clone https://github.com/tianocore/edk2-platforms.git --depth=1
   displayName: Clone sources
 
-- script:  |
-      cd /home/vsts/work/1/edk2
-      make -C BaseTools/
-  displayName: Build BaseTools
+- script: |
+    cd /home/vsts/work/1/edk2
+
+    echo "Patching EDK2 Source"
+    file="BaseTools/Source/C/GenFw/Elf32Convert.c"
+
+    # Check if R_ARM_PC13 already exists
+    if ! grep -q "case R_ARM_PC13:" "$file"; then
+        # Insert after R_ARM_REL32
+        sed -i '/case R_ARM_REL32:/a\        case R_ARM_PC13:' "$file"
+        echo "Inserted 'case R_ARM_PC13:' after 'case R_ARM_REL32:'."
+    else
+        echo "'case R_ARM_PC13:' already exists. No changes made."
+    fi
+
+    file="MdeModulePkg/Universal/Disk/UnicodeCollation/EnglishDxe/UnicodeCollationEng.c"
+
+    # Use sed to replace only if the "Status;" version exists
+    if grep -q "EFI_STATUS  Status;" "$file"; then
+        sed -i 's/EFI_STATUS  Status;/EFI_STATUS  Status = EFI_SUCCESS;/' "$file"
+        echo "Replaced 'EFI_STATUS  Status;' with 'EFI_STATUS  Status = EFI_SUCCESS;'"
+    else
+        echo "Pattern not found, no changes made."
+    fi
+
+    make -C BaseTools/
+  displayName: Patch and Build BaseTools
 
 - script: |
       cd /home/vsts/work/1/HtcLeoPkg
